# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  LintStatus:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: install SwiftLint
      run: brew install swiftlint
      
    - name: Swift lint validation
      run: swiftlint --strict
    # - name: Run tests
    #   run: swift test -v
